services:
  postgres:
    image: postgres:16-alpine
    container_name: logistics-postgres
    environment:
      POSTGRES_USER: logistics_app
      POSTGRES_PASSWORD: devpassword_change_me
      POSTGRES_DB: logistics_asset_tracker
    ports:
      - "5432:5432"
    volumes:
      - logistics-postgres-data:/var/lib/postgresql/data

volumes:
  logistics-postgres-data:
